@startuml tropisticAgentClass
left to right direction

class Sensor {
    -calculation : Float
    --
    +setState(Function) 
    +setMeasurment(Float)
    +getRange() : Integer
    +checkError(Float) : Float
    +calcTDS(Float) : Float
    +sendCalculation(Float) : Float
}

class VernierSensor{
    -range : Integer
    -measurement : Float
    --
    +getMeasurement() : Float
    +setRange(Integer)

}

Sensor <|--VernierSensor
@enduml