@startuml reflexAgentClass

class ReflexAgent {
    -measurement : Float
    -assertion : String
    --
    +setState(Function)
    +requestMeasurement() : String
    +receiveMeasurement(Float)
    +evaluateSample(Float) : string
    +evaluateAssertion(String) : string
}
@enduml