@startuml reflexAgentDeploy

left to right direction

node executable

rectangle tropisticAgent {
     component arduino
} 
rectangle reflexAgent{
    component evaluationSoftware
}

executable -- reflexAgent
reflexAgent -- tropisticAgent : serial transportation

    

@enduml