@startuml reflexAgentDeploy

left to right direction


node arduino[
    <<device>> 
     arduino

    <<artifact>>
Tropistic Agent Measurement Software

]

node computer[
    <<device>> 
     computer

    <<artifact>>
    Reflex Agent Evaluation Software

]

arduino -- computer : serial transportation

    

@enduml