@startuml tropisticAgentClass
left to right direction

class TropisticAgent {
    -calculation : Float
    -range : Integer
    -measurement : Float
    --
    +setState(Function) 
    +setMeasurment(Float)
    +getMeasurement() : Float
    +setRange(Integer)
    +getRange() : Integer
    +checkError(Float) : Float
    +calcTDS(Float) : Float
    +sendCalculation(Float) : Float
}

class ReflexAgent {
    -measurement : Float
    -assertion : String
    --
    +setState(Function)
    +requestMeasurement() : String
    +receiveMeasurement(Float)
    +evaluateSample(Float) : string
    +evaluateAssertion(String) : string
}


TropisticAgent -- ReflexAgent
@enduml