@startuml tropistAgentDeploy
left to right direction

node executable

rectangle tropisticAgent {
     component arduino
} 
rectangle reflexAgent{
    component evaluationSoftware
}

executable -- tropisticAgent
tropisticAgent-- reflexAgent : serial transportation 
@enduml